name: Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  update:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rise-worlds/gha-find-replace-${{ matrix.os }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,${{ env.RELEASE_VERSION }}"
